function jchaos = Charlier_expand_1d(x, coef, order, alpha)
%
% Charlier_expand.m - Evaluates the 1D Charlier-chaos expansion at given data 
%                     points
%
% Syntax:   jchaos = Charlier_expand_1d(x, coef, order, alpha)
% 
% Input :   x  =  data points in matrix form where expansion to be evaluated
%           coef = array with length (P+1) containning expansion coeffcients
%                  of P-th order Jacobi-chaos
%           order = specified order for the expansion to be evaluated; 
%                   if order is not in the range defined by coef (1,P), i.e.,
%                   order>P or <=0, then the full order P from coef will be
%                   used. (Thus, 'order' provides a way to evaluate
%                   the chaos at expansion order lower than P.)
%
% Output:   jchaos = values of expansion at x, stored in the same format as x
%
% NO WARNING MESSAGE IS GIVEN WHEN PAPAMETERS ARE OUT OF RANGE.
%
% Code generated by Dongbin Xiu 5/05/2003.
%

P = length(coef)-1;
if ((order <= 0) | (order > P))
  order = P;
end

jchaos = zeros(size(x));

for i=1:(order+1)
jchaos = jchaos + coef(i)*CharlierF(x, i-1,alpha);
end
