function jmoment = jacobi_moment(n, coef, alpha, beta)
%
% jacobi_moment.m  -  Evaluates the moment of a given Jacobi-chaos expansion
%
% Syntax:   jmoment = jacobi_moment(n, coef, alpha, beta)
%
% Input :   n = n-th moment to be evaluated, n=1 is mean; 2 is variance, etc.
%           coef = array with length (P+1) containing the expansion 
%                  coefficients of P-th order Jacobi-chaos expansion
%           alpha, beta = parameters > -1 of Jacobi-chaos P(x;alpha, beta)
% 
% Output:   jmoment = the n-th moment
%
% NO WARNING MESSAGE IS GIVEN WHEN PAPAMETERS ARE OUT OF RANGE.
%
% Code generated by Dongbin Xiu 01/24/2002.
%

P = length(coef)-1;

np = ceil((P*n+1)/2);
fac =2^(alpha+beta+1)*(gamma(alpha+1)*gamma(beta+1)/gamma(alpha+beta+2));

[z,w] = zwgj(np, alpha, beta);
rv = zeros(size(z));

for i=1:P+1
fp = jacobf(z, i-1, alpha, beta);
rv = rv + coef(i)*fp;
end

jmoment = sum(((rv-coef(1)).^n).*w);
jmoment = jmoment/fac;

